"""OKLab color math, WCAG contrast, and the known "AI look" palette anchors."""
from __future__ import annotations

import numpy as np


def hex_to_rgb(h: str) -> np.ndarray:
    h = h.strip().lstrip("#")
    if len(h) == 3:
        h = "".join(c * 2 for c in h)
    return np.array([int(h[i:i + 2], 16) for i in (0, 2, 4)], dtype=np.float64) / 255.0


def rgb_to_hex(rgb) -> str:
    r, g, b = (int(round(max(0.0, min(1.0, float(c))) * 255)) for c in rgb)
    return f"#{r:02x}{g:02x}{b:02x}"


def srgb_to_linear(c: np.ndarray) -> np.ndarray:
    c = np.asarray(c, dtype=np.float64)
    return np.where(c <= 0.04045, c / 12.92, ((c + 0.055) / 1.055) ** 2.4)


def linear_to_srgb(c: np.ndarray) -> np.ndarray:
    c = np.clip(np.asarray(c, dtype=np.float64), 0, 1)
    return np.where(c <= 0.0031308, c * 12.92, 1.055 * np.power(c, 1 / 2.4) - 0.055)


_M1 = np.array([[0.4122214708, 0.5363325363, 0.0514459929],
                [0.2119034982, 0.6806995451, 0.1073969566],
                [0.0883024619, 0.2817188376, 0.6299787005]])
_M2 = np.array([[0.2104542553, 0.7936177850, -0.0040720468],
                [1.9779984951, -2.4285922050, 0.4505937099],
                [0.0259040371, 0.7827717662, -0.8086757660]])
_M2_INV = np.linalg.inv(_M2)
_M1_INV = np.linalg.inv(_M1)


def rgb_to_oklab(rgb: np.ndarray) -> np.ndarray:
    """rgb: (..., 3) sRGB in 0-1 -> (..., 3) OKLab (L 0-1)."""
    lin = srgb_to_linear(rgb)
    lms = lin @ _M1.T
    return np.cbrt(lms) @ _M2.T


def oklab_to_rgb(lab: np.ndarray) -> np.ndarray:
    lms = np.asarray(lab, dtype=np.float64) @ _M2_INV.T
    lin = (lms ** 3) @ _M1_INV.T
    return linear_to_srgb(lin)


def oklch(lab: np.ndarray) -> tuple[float, float, float]:
    L, a, b = (float(x) for x in lab)
    return L, float(np.hypot(a, b)), float(np.degrees(np.arctan2(b, a)) % 360)


def from_oklch(L: float, C: float, h: float) -> np.ndarray:
    hr = np.radians(h)
    return np.array([L, C * np.cos(hr), C * np.sin(hr)])


def in_gamut(lab: np.ndarray) -> bool:
    lms = np.asarray(lab) @ _M2_INV.T
    lin = (lms ** 3) @ _M1_INV.T
    return bool(np.all(lin >= -1e-4) and np.all(lin <= 1 + 1e-4))


def clamp_chroma(L: float, C: float, h: float) -> np.ndarray:
    """Reduce chroma until the color fits in sRGB."""
    lo, hi = 0.0, C
    if in_gamut(from_oklch(L, C, h)):
        return from_oklch(L, C, h)
    for _ in range(24):
        mid = (lo + hi) / 2
        if in_gamut(from_oklch(L, mid, h)):
            lo = mid
        else:
            hi = mid
    return from_oklch(L, lo, h)


def lab_hex(lab: np.ndarray) -> str:
    return rgb_to_hex(oklab_to_rgb(lab))


def rel_luminance(rgb: np.ndarray) -> float:
    lin = srgb_to_linear(np.asarray(rgb))
    return float(0.2126 * lin[0] + 0.7152 * lin[1] + 0.0722 * lin[2])


def contrast(hex_a: str, hex_b: str) -> float:
    la, lb = rel_luminance(hex_to_rgb(hex_a)), rel_luminance(hex_to_rgb(hex_b))
    hi, lo = max(la, lb), min(la, lb)
    return (hi + 0.05) / (lo + 0.05)


def delta_e(hex_a: str, hex_b: str) -> float:
    return float(np.linalg.norm(rgb_to_oklab(hex_to_rgb(hex_a)) - rgb_to_oklab(hex_to_rgb(hex_b))))


# Palettes that read as generated by default (from Anthropic's frontend-design calibration
# list plus the long-running Tailwind-indigo default). Used only to warn, never to forbid.
CLICHES = [
    {"name": "warm cream + terracotta (the Claude-accent look)", "bg": "#f4f1ea", "accent": "#d97757"},
    {"name": "near-black + acid green", "bg": "#0b0b0b", "accent": "#c6ff3d"},
    {"name": "near-black + vermilion", "bg": "#0b0b0b", "accent": "#ff4d1f"},
    {"name": "white + indigo/violet gradient (Tailwind default)", "bg": "#ffffff", "accent": "#6366f1"},
    {"name": "white + violet gradient", "bg": "#ffffff", "accent": "#8b5cf6"},
]


def cliche_warnings(bg: str, accent: str) -> list[str]:
    out = []
    for c in CLICHES:
        if delta_e(bg, c["bg"]) < 0.045 and delta_e(accent, c["accent"]) < 0.09:
            out.append(c["name"])
    return out
